anchor_version = "0.22.0"

#TODO: user .secret file to address
[programs.localnet]
super_liquidity = "4GpqkriT3ddFLN7dh9e65P2EZRdetqJR7wpMe9nPTpn6"
delphor_oracle_aggregator = "BSVnZFytqxNN5e9UVN434YRWEFXJdpQyyyB8QmXoXdd3"
delphor_oracle = "CSLRinGydCdX4KZs1ngeRQHfdfh1g63g8wwCGUZ4r5j8"

[programs.devnet]
super_liquidity = "4GpqkriT3ddFLN7dh9e65P2EZRdetqJR7wpMe9nPTpn6"
delphor_oracle_aggregator = "BSVnZFytqxNN5e9UVN434YRWEFXJdpQyyyB8QmXoXdd3"
delphor_oracle = "CSLRinGydCdX4KZs1ngeRQHfdfh1g63g8wwCGUZ4r5j8"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "mocha -r ts-node/register --verbose -t 1000000 tests/super_liquidity.js"