anchor_version = "0.22.0"

#TODO: user .secret file to address
[programs.localnet]
super_liquidity = "4FCQYxXVaK1aWE7gTLhTB5CwyjZGRFPFJstJdcNsoqck"
delphor_oracle_aggregator = "HbyTY89Se2c8Je7KDKHVjUEGN2sAruFAw3S3NwubzeyU"
delphor_oracle = "3xzPckGW3b771JsrcfQyRYzdPmsYgHjNohupSKHqjEV3"

[programs.devnet]
super_liquidity = "4FCQYxXVaK1aWE7gTLhTB5CwyjZGRFPFJstJdcNsoqck"
delphor_oracle_aggregator = "HbyTY89Se2c8Je7KDKHVjUEGN2sAruFAw3S3NwubzeyU"
delphor_oracle = "3xzPckGW3b771JsrcfQyRYzdPmsYgHjNohupSKHqjEV3"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "mocha -r ts-node/register --verbose -t 1000000 tests/super_liquidity.js"