anchor_version = "0.19.0"

#TODO: user .secret file to address
[programs.localnet]
super_liquidity = "GD7B9rYsWeuLyYMTDa9z5C7osPg5gMDZZZqpF5NEmGXD"

[programs.devnet]
super_liquidity = "GD7B9rYsWeuLyYMTDa9z5C7osPg5gMDZZZqpF5NEmGXD"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "mocha --verbose -t 1000000 tests/"
