anchor_version = "0.22.0"

#TODO: user .secret file to address
[programs.localnet]
super_liquidity = "4yD8QCX2WfXMQ6Jmo16o3YvZqYWpTd7KfGUqJ57Bwkpm"
delphor_oracle_aggregator = "Ev8Q73RFWaDPTc1YBaa6Zu7J2XmQMQy3aQcdyb3Z64Qd"
delphor_oracle = "orcGZ2qdQPdF2CpwP6kHD6AJHA5oSZiFFDBmNEHyyS4"

[programs.devnet]
super_liquidity = "4yD8QCX2WfXMQ6Jmo16o3YvZqYWpTd7KfGUqJ57Bwkpm"
delphor_oracle_aggregator = "Ev8Q73RFWaDPTc1YBaa6Zu7J2XmQMQy3aQcdyb3Z64Qd"
delphor_oracle = "orcGZ2qdQPdF2CpwP6kHD6AJHA5oSZiFFDBmNEHyyS4"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "mocha -r ts-node/register --verbose -t 1000000 tests/super_liquidity.js"